# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e0d64cb4ad067bea0930bb965a58f3dbdea098ba05f4ae364cc3d625b283f5f6bef50460420cec66b6ccfee16af083578a6073c1a3be7ae7f90a17193e90bb3

test:
  secret_key_base: d589136932778f085ddaf22ed880540be27348f4bd8364fc7203148254fcd61c9b182d39dfd6f80b9d65a3280aa67ae02587cffa9b23d25f24ad7967099c1d0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
